global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  #evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
- job_name: 'blackbox'
  metrics_path: /probe
  params:
      module: [http_2xx]
  static_configs:
      - targets:
          - http://github.com
          - http://google.com
          - http://www.deepl.com
          - http://www.youtube.com/
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: prometheus-blackbox:9115  # The blackbox exporter's real hostname:port.

- job_name: 'grafana'
  metrics_path: /metrics
  static_configs:
    - targets:
        - 'zabbix-grafana:3000'
  basic_auth:
    username: 'admin'
    password: 'grafana'