global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'hostlinux'
    static_configs:
      - targets: ['192.168.0.100:9090']
  
  #- job_name: 'mysql-exporter'
  #  static_configs:
  #    - targets: ['mysql-exporter:9104']
  
  # - job_name: 'nginx-exporter'
  #  static_configs:
  #    - targets: ['nginx:9113']
